telegram_token: ""
openai_api_key: ""
payment_provider_token: ""
use_chatgpt_api: true
allowed_telegram_usernames: []  # if empty, the bot is available to anyone. pass a username string to allow it and/or user ids as integers
new_dialog_timeout: 600  # new dialog starts after timeout (in seconds)
new_dialog_count: 5
enable_message_streaming: true  # if set, messages will be shown to user word-by-word
max_free_messages: 10
mailing_message: |
  Представляем вашему вниманию новейшую модель GPT-4o от OpenAI! Это самая передовая, интеллектуальная и быстрая модель, которая поможет вам готовиться к экзаменам ещё эффективнее, точнее и быстрее.
  
  P.S. Если в ваших настройках уже выбрана модель GPT-4, то вам не нужно предпринимать никаких дополнительных действий – новейшая версия сразу же будет доступна вам!

currency: "RUB"

levels:
  - id: 0
    model: 'gpt-3.5-turbo'
    title: 'Подписка на бота GPT3.5'
    description: 'Безлимитное общение с ботом на'
    price: 149
    subscribe_period: 31 # days
    subscribe_period_text: "1 месяц"
  - id: 1
    model: 'gpt-3.5-turbo'
    title: 'Подписка на бота GPT3.5'
    description: 'Безлимитное общение с ботом на'
    price: 249
    subscribe_period: 92 # days
    subscribe_period_text: "3 месяца"
  - id: 2
    model: 'gpt-4o'
    title: 'Подписка на бота (GPT3.5 + GPT4o)'
    description: 'Безлимитное общение с ботом GPT3.5 + GPT4o на'
    price: 399
    subscribe_period: 31 # days
    subscribe_period_text: "1 месяц"
  - id: 3
    model: 'gpt-4o'
    title: 'Подписка на бота (GPT3.5 + GPT4o)'
    description: 'Безлимитное общение с ботом GPT3.5 + GPT4o на'
    price: 1099
    subscribe_period: 92 # days
    subscribe_period_text: "3 месяца"

# prices
chatgpt_price_per_1000_tokens: 0.002
gpt_price_per_1000_tokens: 0.02
whisper_price_per_1_min: 0.006